# Generated by Django 5.2.8 on 2025-11-14 12:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('house', models.CharField(max_length=10, verbose_name='Дом')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialType',
            fields=[
                ('material_type', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Тип материала')),
                ('defect_percentage', models.FloatField(verbose_name='Процент брака материала')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerType',
            fields=[
                ('id_partner_type', models.AutoField(primary_key=True, serialize=False)),
                ('partner_type', models.CharField(max_length=50, verbose_name='Тип партнера')),
            ],
        ),
        migrations.CreateModel(
            name='PostalCode',
            fields=[
                ('postal_code', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Почтовый индекс')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100, verbose_name='Тип продукции')),
                ('product_type_coefficient', models.FloatField(verbose_name='Коэффициент типа продукции')),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('inn', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='ИНН')),
                ('partner_name', models.CharField(max_length=255, verbose_name='Наименование партнера')),
                ('director', models.CharField(max_length=255, verbose_name='Директор')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Введите корректный email адрес.')], verbose_name='Электронная почта партнера')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message="Телефон должен быть в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон партнера')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('legal_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.house', verbose_name='Юридический адрес партнера')),
                ('partner_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.partnertype', verbose_name='Тип партнера')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('article', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Артикул')),
                ('product_name', models.CharField(max_length=255, verbose_name='Наименование продукции')),
                ('min_partner_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная стоимость для партнера')),
                ('material', models.ManyToManyField(to='masterpol.materialtype', verbose_name='Тип материала')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.producttype', verbose_name='Тип продукции')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(verbose_name='Количество продукции')),
                ('sale_date', models.DateTimeField(verbose_name='Дата продажи')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.partner', verbose_name='Наименование партнера')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.product', verbose_name='Продукция')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Код региона')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('postal_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.postalcode', verbose_name='Почтовый индекс')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('settlement', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.region', verbose_name='Регион')),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.settlement', verbose_name='Населенный пункт')),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masterpol.street', verbose_name='Улица'),
        ),
    ]
